version: "3.5"
services:
  xtractDB:
      image: postgres
      shm_size: 512mb
      command: postgres -c 'max_connections=1000' -c 'shared_buffers=256MB'
      restart: always
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        # - PGDATA=/var/lib/postgresql/data/pgdata
      volumes:
        - ./postgres/pgdata:/var/lib/postgresql/data
        - /home/ubuntu/customer_mapping/Stockwell:/home/customer_mapping/Stockwell
        # - /var/lib/postgresql/data/pgdata
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_DOCKER_PORT}
  # pgbackups:
  #   build: backup
  #   image: ${COMPOSE_PROJECT_NAME}/backup
  #   restart: always
  #   volumes:
  #     - ./backup:/backups
  #   links:
  #     - xtractDB:xtractDB
  #   depends_on:
  #     - xtractDB
  #   environment:
  #     - POSTGRES_HOST=xtractDB
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
  #     - SCHEDULE=@every 0h30m00s
  #     - BACKUP_KEEP_DAYS=7
  #     - BACKUP_KEEP_WEEKS=4
  #     - BACKUP_KEEP_MONTHS=6